kernel_modules:
  # Example of a builtin module
  # What should happen: it will not be loaded, because it already is loaded
  - name: acpi-cpufreq
    kernel_build_opt: CONFIG_X86_ACPI_CPUFREQ

  - name: amd_pstate
    kernel_build_opt: CONFIG_X86_AMD_PSTATE

  - name: msr
    kernel_build_opt: CONFIG_X86_MSR

  # Example of a pluggable module that ships with kernel
  # What should happen: it will be built from source and loaded
  - name: cpuid
    kernel_build_opt: CONFIG_X86_CPUID
    git_repo: https://github.com/erman-dev/cpuid-dkms.git
    force_build: True

  # Example of modules that need to be built
  # What should happen: it will be built and then loaded
  - name: amd_hsmp
    git_repo: https://github.com/amd/amd_hsmp.git
    git_repo_tag: f34b98fb70b67a7908f32d4d6da5a2ee89857b08

  - name: amd_energy
    git_repo: https://github.com/amd/amd_energy.git
    force_build: true
    cpu_constraints:
      cpu_inclusions:
        - family: 0x19
          model:
            - range:
                start: 0x00
                end: 0x0F
            - range:
                start: 0x30
                end: 0x3F
        - family: 0x19
          model:
            - range:
                start: 0x10
                end: 0x1F
            - range:
                start: 0xA0
                end: 0xAF
            - range:
                start: 0x90
                end: 0x9F
        - family: 0x1A
          model:
            - range:
                start: 0x00
                end: 0x1F
    patches:
      - amd_energy_kernel_version.patch
