---
- name: Check if git and dkms are installed
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Ensure git is installed
      ansible.builtin.package:
        name: git
        state: present
      register: git_installation
      notify:
        - Report git status

    - name: Ensure dkms is installed
      ansible.builtin.package:
        name: dkms
        state: present
      register: dkms_installation
      notify:
        - Report dkms status

    - name: Check kernel version
      ansible.builtin.debug:
        msg: "Kernel version {{ ansible_kernel }} is lower than 5.8 on {{ ansible_hostname }}"
      when: ansible_kernel is version('5.8', '<')

    - name: Fail the playbook if kernel version is lower than 5.8
      ansible.builtin.fail:
        msg: "Kernel version {{ ansible_kernel }} is lower than 5.8 on {{ ansible_hostname }}"
      when: ansible_kernel is version('5.8', '<')

  handlers:
    - name: Report git status
      ansible.builtin.debug:
        msg: >
          {% if git_installation.changed %}
          git was not installed on {{ ansible_hostname }} and has been installed now.
          {% elif git_installation.failed %}
          git installation failed on {{ ansible_hostname }}.
          {% else %}
          git was already installed on {{ ansible_hostname }}.
          {% endif %}

    - name: Report dkms status
      ansible.builtin.debug:
        msg: >
          {% if dkms_installation.changed %}
          dkms was not installed on {{ ansible_hostname }} and has been installed now.
          {% elif dkms_installation.failed %}
          dkms installation failed on {{ ansible_hostname }}.
          {% else %}
          dkms was already installed on {{ ansible_hostname }}.
          {% endif %}
