---
- name: Test installing kernel modules
  hosts: all
  gather_facts: false
  tasks:
    - include_role: 
        name: manage_kernel_modules
      vars:
        kernel_modules:
          - name: psmouse
            params: "rate=100,resolution=800"
          - name: amd_hsmp
            git_repo: https://github.com/amd/amd_hsmp.git
          - name: amd_energy
            git_repo: https://github.com/amd/amd_energy.git