---
# Detect what kind of module is being loaded - builtin, loadable or missing
- name: "Detect if the module is present in kernel config : {{ insert_kernel_module_data.name }}"
  vars:
    kernel_conf_file: "/boot/config-{{ ansible_facts['kernel'] }}"
  ansible.builtin.shell: |
    set -o pipefail
    if grep -q '^{{ insert_kernel_module_data.kernel_build_opt }}=' {{ kernel_conf_file }}; then
      grep '^{{ insert_kernel_module_data.kernel_build_opt }}=' {{ kernel_conf_file }} | awk -F'=' '{print $2}';
    fi
  args:
    executable: /bin/bash
  register: kernel_config
  changed_when: false
  when:
    - insert_kernel_module_data.kernel_build_opt is defined

# If the module was not found in the kernel config, try checking it with modinfo in case
# it was already installed with DKMS
- name: "Get module info with modinfo : {{ insert_kernel_module_data.name }}"
  ansible.builtin.command: "modinfo {{ insert_kernel_module_data.name }}"
  register: modinfo
  failed_when: false
  changed_when: false
  when:
    - "insert_kernel_module_data.kernel_build_opt is not defined or kernel_config.stdout == ''"

# Decide what kind of kernel module it is
# 1. =y was present in kernel config, so it is a builtin module
# 2. =m was present in kernel config, so it is a loadable module that ships with kernel
#     or module was not found in the kernel config, but found with modinfo, so it was installed already with DKMS, so it can be loaded
# 3. module was not found in the kernel config and not found with modinfo, so it is missing
#     or insert_kernel_module_data.kernel_build_opt is not defined -> module was for sure not found as it was expected this module to not be
#     part of kernel when the option was not defined
# 4. None of the above, the user should examine the module manually
- name: "Use modinfo results to get the module type : {{ insert_kernel_module_data.name }}"
  vars:
    kernel_config_output: "{{ kernel_config.stdout | default('') }}"
    modinfo_output: "{{ modinfo.stdout | default('') }}"
    modinfo_error_output: "{{ modinfo.stderr | default('') }}"
  ansible.builtin.set_fact:
    module_type: |-
      {%- if 'y' in kernel_config_output -%}
        builtin
      {%- elif 'm' in kernel_config_output or '/lib/modules' in modinfo_output -%}
        loadable
      {%- elif 'not found' in modinfo_error_output or insert_kernel_module_data.kernel_build_opt is not defined -%}
        missing
      {%- else -%}
        error
      {%- endif -%}

- name: "Raise error if the module_type was not detected : {{ insert_kernel_module_data.name }}"
  ansible.builtin.fail:
    msg: |-
      The play was unable to determine the type of the module (builtin, loadable, missing).
      This is most likely due kernel_build_opt missing from /boot/config or problem with modinfo.
      Please check your insert_kernel_module_data config. Your current config is:

      {{ insert_kernel_module_data | to_nice_yaml }}
  when: module_type == "error"
