# Takes in a list of kernel_modules and return two lists
# loadable_modules - list of modules already available to the kernel
# unloadable_module - list of module unavailable to the kernel
---

- name: Check which kernel modules are present
  command: "modinfo {{ item.name }}"
  loop: "{{ kernel_modules }}"
  register: modinfo
  failed_when: false
  changed_when: false

- name: Sort modules by results of modinfo
  vars:
    unloadable_modules: "{{ modinfo.results | selectattr('stderr', 'match', '(.*)not found\\.$') | map(attribute='item') }}"
    loadable_modules: "{{ modinfo.results | selectattr('rc', 'equalto', 0) | map(attribute='item') }}"
    problematic_modules: "{{ kernel_modules | difference(loadable_modules) | difference(unloadable_modules) }}"
  set_fact:
    unloadable_modules: "{{ unloadable_modules }}"
    loadable_modules: "{{ loadable_modules }}"
    problematic_modules: "{{ kernel_modules | difference(loadable_modules) | difference(unloadable_modules) }}"

- fail:
    msg: >-
      Some kernel modules reported errors other than NOT FOUND when inspected by modinfo.
      Please address these modules manually: {{ problematic_modules | map(attribute='name') | join(', ') }}"
  when: problematic_modules | length > 0
