---
# Loads all kernel modules sent to this role in "kernel_modules" variable

- import_tasks: check_modules.yml

# Import all modules using modprobe
- include_tasks: load_modules.yml
  vars:
    modules_to_load: "{{ loadable_modules }}"
  when: loadable_modules | length > 0

# If there are some modules that were unloadable
# build them using DKMS and then load them using moodprobe
- block:
    - include_tasks: build_module.yml
      loop: "{{ unloadable_modules }}"

    - include_tasks: load_modules.yml
      vars:
        modules_to_load: "{{ unloadable_modules }}"
  when: unloadable_modules | length > 0
