kernel_modules:
  # Example of a builtin module 
  # What should happen: it will not be loaded, because it already is loaded
  - name: acpi-cpufreq
    kernel_opt: CONFIG_X86_ACPI_CPUFREQ
  
  # Example of a pluggable module that ships with kernel 
  # What should happen: it will be loaded
  - name: cpuid
    kernel_opt: "CONFIG_X86_CPUID"

  # Example of modules we have to build 
  # What should happen: it will be built and then loaded
  - name: amd_hsmp
    kernel_opt: "xxx" # I was not able to find hat would be the kernel opt for this module.
    git_repo: https://github.com/amd/amd_hsmp.git
    patches:
      - ./amd_energy_fix1.patch
      - ./amd_energy_fix2.patch
      - ./amd_energy_fix3.patch

  - name: amd_energy
    kernel_opt: "xxx" # I was not able to find hat would be the kernel opt for this module.
    git_repo: https://github.com/amd/amd_energy.git