kernel_modules:
  # Example of a builtin module 
  # What should happen: it will not be loaded, because it already is loaded
  - name: acpi-cpufreq

  # Example of a pluggable module that ships with kernel 
  # What should happen: it will be loaded
  - name: cpuid

  # Example of modules we have to build 
  # What should happen: it will be built and then loaded
  - name: amd_hsmp
    git_repo: https://github.com/amd/amd_hsmp.git
    git_repo_tag: f34b98fb70b67a7908f32d4d6da5a2ee89857b08
    force_build: True
    patches:
      - amd_hsmp_fix1.patch

  - name: amd_energy
    git_repo: https://github.com/amd/amd_energy.git
    force_build: True
