---
# This role verifies AMD settings in BIOS and possibly in grub

- name: Check amd_pstate driver setting in sysfs value and provide fix message if incorrect
  block:
    - name: Read amd_pstate sysfs value
      ansible.builtin.command: cat /sys/devices/system/cpu/amd_pstate/status
      register: sysfs_amd_pstate_output
      changed_when: false

    - name: Check if amd_pstatet sysfs value is correct
      ansible.builtin.assert:
        that:
          - sysfs_amd_pstate_output.stdout == "passive"
        fail_msg: 'The driver amd_pstate setting is not set correctly. Add into /etc/default/grub: GRUB_CMDLINE_LINUX_DEFAULT="amd_pstate=passive"'
        success_msg: "The driver amd_pstate setting is set correctly."

- name: Check CPU CPPC setting using /proc/cpuinfo
  block:
    - name: Read cppc in /proc/cpuinfo
      ansible.builtin.shell: |
        set -o pipefail && grep cppc /proc/cpuinfo | uniq
      args:
        executable: /bin/bash
      register: cpuinfo_cppc_output
      changed_when: false

    - name: Verify CPU cppc setting
      ansible.builtin.assert:
        that:
          - cpuinfo_cppc_output.stdout | length > 0
        fail_msg: "BIOS CPPC setting is not correct. Enable CPPC in BIOS."
        success_msg: "BIOS CPPC setting is correct."

- name: Check CPU Monitor and Mwait setting using /proc/cpuinfo
  block:
    - name: Read mwaitx in /proc/cpuinfo
      ansible.builtin.shell: |
        set -o pipefail && grep mwaitx /proc/cpuinfo | uniq
      args:
        executable: /bin/bash
      register: cpuinfo_mwaitx_output
      changed_when: false

    - name: Verify CPU mwaitx setting
      ansible.builtin.assert:
        that:
          - cpuinfo_mwaitx_output.stdout | length > 0
        fail_msg: "BIOS Monitor and Mwait setting is not correct. Enable Monitor and Mwait in BIOS."
        success_msg: "BIOS Monitor and Mwait setting is correct."
