---
- name: Check amd_pstate driver setting in sysfs and GRUB
  become: true
  block:
    - name: Read amd_pstate sysfs value
      ansible.builtin.command: cat /sys/devices/system/cpu/amd_pstate/status
      register: sysfs_amd_pstate_output
      changed_when: false

    - name: Set fact for amd_pstate sysfs check
      ansible.builtin.set_fact:
        amd_pstate_sysfs_correct: "{{ sysfs_amd_pstate_output.stdout == 'passive' }}"

    - name: Configure amd_pstate driver in GRUB
      when: not amd_pstate_sysfs_correct
      block:
        - name: Check for correct amd_pstate parameter in GRUB
          ansible.builtin.shell: grep -E '^{{ grub_cmdline }}=.*amd_pstate=passive' /etc/default/grub
          register: grub_check
          changed_when: false
          failed_when: false

        - name: Add or modify amd_pstate parameter in GRUB
          ansible.builtin.lineinfile:
            path: /etc/default/grub
            regexp: '^{{ grub_cmdline }}='
            line: '{{ grub_cmdline }}="amd_pstate=passive"'
            state: present
          become: true
          when: grub_check.rc != 0
          register: add_parameter

        - name: Update GRUB
          ansible.builtin.command: update-grub
          become: true
          when: add_parameter.changed
          changed_when: true
          register: grub_updated

    - name: Fail if reboot is required
      ansible.builtin.fail:
        msg: >-
          The driver amd_pstate setting is not set correctly. Added: {{ grub_cmdline }}="amd_pstate=passive"
          to /etc/default/grub and executed: update-grub; please execute reboot on host {{ ansible_hostname }} to apply changes
      when: (grub_updated is defined and grub_updated.changed) or not amd_pstate_sysfs_correct
